# generated by datamodel-codegen:
#   filename:  keymap.json
#   timestamp: 2023-09-02T06:02:54+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class Model(BaseModel):
    keyboard: str
    keymap: str
    layout: str
    layers: List[List[str]]
